
-- Write SQL queries to perform the following tasks using the Sakila database:
 
use sakila;

-- List the number of films per category.

SELECT 
    c.name AS 'Category Name',
    COUNT(fc.film_id) AS 'Number of Films'
FROM
    sakila.film_category AS fc
        JOIN
    sakila.category AS c ON fc.category_id = c.category_id
GROUP BY c.name;
-- Retrieve the store ID, city, and country for each store.

SELECT 
    store_id AS 'Store', city AS 'City', country AS 'Country'
FROM
    sakila.store
        JOIN
    sakila.address ON sakila.store.address_id = sakila.address.address_id
        JOIN
    sakila.city ON sakila.address.city_id = sakila.city.city_id
        JOIN
    sakila.country ON sakila.city.country_id = sakila.country.country_id;
    
-- Calculate the total revenue generated by each store in dollars.

SELECT 
    s.store_id AS 'Store', SUM(p.amount) AS 'Revenue'
FROM
    sakila.payment AS p
        JOIN
    sakila.staff AS s ON s.staff_id = p.staff_id
        JOIN
    sakila.store AS st ON st.manager_staff_id = s.staff_id
GROUP BY s.store_id;

-- Determine the average running time of films for each category.

SELECT
    c.category_id AS "Category ID",
    c.name AS "Category Name",
    ROUND(AVG(f.length), 2) AS "Average Running Time"
FROM
    category AS c
JOIN
    film_category AS fc ON c.category_id = fc.category_id
JOIN
    film AS f ON fc.film_id = f.film_id
GROUP BY
    c.category_id, c.name;

-- Bonus:

-- Identify the film categories with the longest average running time.

SELECT 
    c.category_id AS 'Category ID',
    c.name AS 'Category Name',
    ROUND(AVG(f.length), 2) AS 'Average Running Time'
FROM
    category AS c
        JOIN
    film_category AS fc ON c.category_id = fc.category_id
        JOIN
    film AS f ON fc.film_id = f.film_id
GROUP BY c.category_id , c.name
ORDER BY ROUND(AVG(f.length), 2) DESC
LIMIT 5;

-- Display the top 10 most frequently rented movies in descending order.

SELECT
    film.film_id AS "Film ID",
    film.title AS "Movie",
    COUNT(rental.rental_id) AS "Times rented"
FROM
    film
JOIN
    inventory ON film.film_id = inventory.film_id
JOIN
    rental ON inventory.inventory_id = rental.inventory_id
GROUP BY
    film.film_id, film.title
ORDER BY
    COUNT(rental.rental_id) DESC
LIMIT
    10;
